// Gemeinsame Aktienliste für die Website (script.js) und den News-Abruf (scripts/fetch-news.mjs).
// [Ticker, Anzeigename, Suchausdruck (optional, GDELT-/Google-Syntax), weitere Suchbegriffe (optional)]
window.STOCKS = [
  ["AAPL", "Apple"], ["MSFT", "Microsoft"], ["NVDA", "Nvidia"], ["AMZN", "Amazon"],
  ["GOOGL", "Alphabet", "(Alphabet OR Google)", ["GOOG", "Google"]],
  ["META", "Meta Platforms", '("Meta Platforms" OR Facebook)', ["Meta", "Facebook"]],
  ["TSLA", "Tesla"], ["NFLX", "Netflix"],
  ["AMD", "AMD", '(AMD OR "Advanced Micro Devices")', ["Advanced Micro Devices"]],
  ["INTC", "Intel"], ["AVGO", "Broadcom"], ["PLTR", "Palantir"], ["ORCL", "Oracle"],
  ["CRM", "Salesforce"], ["ADBE", "Adobe"], ["QCOM", "Qualcomm"], ["IBM", "IBM"],
  ["ASML", "ASML"], ["BA", "Boeing"], ["DIS", "Disney"], ["KO", "Coca-Cola"],
  ["PEP", "PepsiCo"], ["MCD", "McDonald's", '("McDonald\'s" OR McDonalds)', ["McDonalds"]],
  ["NKE", "Nike"], ["SBUX", "Starbucks"], ["WMT", "Walmart"],
  ["JPM", "JPMorgan", '(JPMorgan OR "JP Morgan")', ["JP Morgan"]],
  ["V", "Visa"], ["MA", "Mastercard"], ["PYPL", "PayPal"], ["UBER", "Uber"],
  ["BABA", "Alibaba"], ["BRK.B", "Berkshire Hathaway", null, ["BRK", "Berkshire"]],
  ["LLY", "Eli Lilly"], ["NVO", "Novo Nordisk"], ["PFE", "Pfizer"],
  ["JNJ", "Johnson & Johnson"], ["XOM", "ExxonMobil", '(ExxonMobil OR "Exxon Mobil")', ["Exxon"]],
  ["CVX", "Chevron"],
  ["SAP", "SAP"], ["SIE", "Siemens"], ["ENR", "Siemens Energy"], ["ALV", "Allianz"],
  ["DTE", "Deutsche Telekom", null, ["Telekom"]], ["DBK", "Deutsche Bank"],
  ["CBK", "Commerzbank"], ["MUV2", "Munich Re", '("Munich Re" OR "Münchener Rück")', ["Münchener Rück"]],
  ["BAS", "BASF"], ["BAYN", "Bayer"], ["ADS", "Adidas"], ["BMW", "BMW"],
  ["MBG", "Mercedes-Benz", null, ["Mercedes"]], ["VOW3", "Volkswagen", null, ["VW", "VOW"]],
  ["P911", "Porsche"], ["RHM", "Rheinmetall"], ["IFX", "Infineon"], ["AIR", "Airbus"],
  ["DHL", "DHL Group", '("DHL Group" OR "Deutsche Post")', ["Deutsche Post", "DHL"]],
  ["RWE", "RWE"], ["EOAN", "E.ON", '("E.ON" OR Eon)', ["Eon"]],
  ["HNR1", "Hannover Rück", '("Hannover Re" OR "Hannover Rück")', ["Hannover Re"]],
  ["ZAL", "Zalando"], ["LIN", "Linde"], ["MRK", "Merck"], ["HEN3", "Henkel"],
  ["BEI", "Beiersdorf"], ["DB1", "Deutsche Börse"], ["CON", "Continental"],
  ["SHL", "Siemens Healthineers", null, ["Healthineers"]], ["MTX", "MTU Aero Engines", null, ["MTU"]],
  ["HEI", "Heidelberg Materials"], ["SY1", "Symrise"], ["QIA", "Qiagen"], ["VNA", "Vonovia"],
  ["BNR", "Brenntag"], ["SRT3", "Sartorius"], ["FRE", "Fresenius"]
];
